"""final

Revision ID: dfaf417aada3
Revises: 1978fc95c779
Create Date: 2026-03-03 18:15:34.222571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfaf417aada3'
down_revision: Union[str, Sequence[str], None] = '1978fc95c779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_Post_userId'), table_name='Post')
    op.create_index(op.f('ix_Post_user_id'), 'Post', ['user_id'], unique=False)
    op.drop_constraint(op.f('Post_userId_fkey'), 'Post', type_='foreignkey')
    op.create_foreign_key(None, 'Post', 'User', ['user_id'], ['id'])
    op.drop_column('Post', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Post', type_='foreignkey')
    op.create_foreign_key(op.f('Post_userId_fkey'), 'Post', 'User', ['userId'], ['id'])
    op.drop_index(op.f('ix_Post_user_id'), table_name='Post')
    op.create_index(op.f('ix_Post_userId'), 'Post', ['userId'], unique=False)
    op.drop_column('Post', 'user_id')
    # ### end Alembic commands ###
