"""final

Revision ID: ea15907a11fd
Revises: 261151487c37
Create Date: 2026-03-03 18:00:28.162625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea15907a11fd'
down_revision: Union[str, Sequence[str], None] = '261151487c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('content', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_Post_Content'), table_name='Post')
    op.create_index(op.f('ix_Post_content'), 'Post', ['content'], unique=False)
    op.drop_column('Post', 'Content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('Content', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_Post_content'), table_name='Post')
    op.create_index(op.f('ix_Post_Content'), 'Post', ['Content'], unique=False)
    op.drop_column('Post', 'content')
    # ### end Alembic commands ###
