"""Initial tables

Revision ID: eda5bc565f4d
Revises: 
Create Date: 2026-03-03 12:51:37.970025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eda5bc565f4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('passwrod', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('FARMER', 'EXPERT', name='Role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=False)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_name'), 'User', ['name'], unique=False)
    op.create_index(op.f('ix_User_passwrod'), 'User', ['passwrod'], unique=False)
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Content', sa.String(length=500), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Post_Content'), 'Post', ['Content'], unique=False)
    op.create_index(op.f('ix_Post_dislikes'), 'Post', ['dislikes'], unique=False)
    op.create_index(op.f('ix_Post_id'), 'Post', ['id'], unique=False)
    op.create_index(op.f('ix_Post_likes'), 'Post', ['likes'], unique=False)
    op.create_index(op.f('ix_Post_userId'), 'Post', ['userId'], unique=False)
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Comment_content'), 'Comment', ['content'], unique=False)
    op.create_index(op.f('ix_Comment_id'), 'Comment', ['id'], unique=False)
    op.create_index(op.f('ix_Comment_post_id'), 'Comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_Comment_user_id'), 'Comment', ['user_id'], unique=False)
    op.create_table('Image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['Comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Image_comment_id'), 'Image', ['comment_id'], unique=False)
    op.create_index(op.f('ix_Image_id'), 'Image', ['id'], unique=False)
    op.create_index(op.f('ix_Image_imageUrl'), 'Image', ['imageUrl'], unique=False)
    op.create_index(op.f('ix_Image_post_id'), 'Image', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Image_post_id'), table_name='Image')
    op.drop_index(op.f('ix_Image_imageUrl'), table_name='Image')
    op.drop_index(op.f('ix_Image_id'), table_name='Image')
    op.drop_index(op.f('ix_Image_comment_id'), table_name='Image')
    op.drop_table('Image')
    op.drop_index(op.f('ix_Comment_user_id'), table_name='Comment')
    op.drop_index(op.f('ix_Comment_post_id'), table_name='Comment')
    op.drop_index(op.f('ix_Comment_id'), table_name='Comment')
    op.drop_index(op.f('ix_Comment_content'), table_name='Comment')
    op.drop_table('Comment')
    op.drop_index(op.f('ix_Post_userId'), table_name='Post')
    op.drop_index(op.f('ix_Post_likes'), table_name='Post')
    op.drop_index(op.f('ix_Post_id'), table_name='Post')
    op.drop_index(op.f('ix_Post_dislikes'), table_name='Post')
    op.drop_index(op.f('ix_Post_Content'), table_name='Post')
    op.drop_table('Post')
    op.drop_index(op.f('ix_User_passwrod'), table_name='User')
    op.drop_index(op.f('ix_User_name'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
