"""final

Revision ID: f7eaa0fa616d
Revises: 8100af1c4b93
Create Date: 2026-03-03 15:57:47.833932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7eaa0fa616d'
down_revision: Union[str, Sequence[str], None] = '8100af1c4b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_User_passwrod'), table_name='User')
    op.create_index(op.f('ix_User_password'), 'User', ['password'], unique=False)
    op.drop_column('User', 'passwrod')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('passwrod', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_User_password'), table_name='User')
    op.create_index(op.f('ix_User_passwrod'), 'User', ['passwrod'], unique=False)
    op.drop_column('User', 'password')
    # ### end Alembic commands ###
